### ISSUE TITLE
"No External Field Detected" and Does # of edges == ground_state_energy?

### ISSUE THREAD

**Issue by robliou** [mcmahon-lab/cim-optimizer#2]
Hello!

Sorry to bother again, but two additional questions I came across while doing further testing:

1) When running the ising test, the first line of output I see is:

``""No External Field Detected"``

![image](https://github.com/mcmahon-lab/cim-optimizer/assets/81087205/eef77976-7a64-404d-89ce-bf2c6f698004)

My basic understanding of how CIM machines work is that the External Field is critical to how the CIM arrives at an answer. Therefore, I'm not sure if the CIM is running properly... is my understanding of how CIM works incorrect, or am I missing a parameter somewhere in my formula?

Secondly, running the Ising function also returns the ``ground_state_energy`` of the system. I am wondering if this ``ground_state_energy`` == the # of edges between vertices in different sets (i.e. number of cut edges), or does an additional conversion need to be done in order to return the number of cut edges? (For reference, I am attempting to do testing on a 25-vertex Max Cut problem. The optimum number of cut edges is 36, but running the CIM optimizer only returns a ```ground_state_energy``` of -27?)

Thanks you again,

**Comment by robliou** [comment]
Apologies, it appears I didn't read the documentation as thoroughly as I should have!

Per Example 1:

```When the MAX-CUT problem is reformatted into an Ising problem, **there is no external field**, so either the CAC solver or the AHC no external field solver can be used.```

So, that answers the 'No External Field Detected' issue. As for the # of edges equalling ground_state_energy, per the basic Ising Hamiltonian formula, the answer is clearly no. A conversion would need to be done to substitute   xixj with (1-xixj)/2 to get to number of edges from ground state.

Not a huge deal, and fairly easily performed from my end. Let me know if you'd like for me to create a pull request for this.

Otherwise, please feel free to close this issue! 

Thanks and Best,

**Comment by tylertking** [comment]
Thanks again for your feedback and I'm glad you were able to fix your issue! I discussed integrating the conversion you suggested with @francisjchen, and we agreed that this idea might be a bit out of scope for cim-optimizer. 

We appreciate your feedback, and if you have any other suggestions feel free to reach out!
